name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test-py:
    runs-on: ubuntu-latest
    
    environment:
      name: dev
      
    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
        
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --trusted-host pypi.python.org pika pymongo requests
        
    - name: Run tests
      env:
        MONGODB_HOST: localhost
        SENSOR_LOCATION: roma
        SENSOR_LONGITUDE: 11.342616
        SENSOR_LATITUDE: 44.494887
        FREQUENCY: 10
        API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
      run: |
        python -m unittest discover -s ./tests -p '*_test.py'
  
  test-js:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        env:
          MONGODB_HOST: test-mongo
        ports:
          - 27018:27017

    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18
    - name: Install JavaScript dependencies
      working-directory: app-backend
      run: npm ci
    - name: Run JavaScript tests
      working-directory: app-backend
      run: npm test
